AWSTemplateFormatVersion: '2010-09-09'
Description: Create IAM Roles for SageMaker Studio and Lambda SAML function

Parameters: 
  NetworkPrivateSubnet: 
    Type: String
  EnvironmentName:
    Type: String  

Resources:

  SageMakerExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: SageMakerExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: SageMakerExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                  - 's3:ListBucket'
                Resource: 'arn:aws:s3:::*'
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess    
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName        

  SAMLBackEndLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: RestrictSageMakertoInternalIP
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:CreatePresignedDomainUrl'
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:user-profile/*/*'
              - Effect: Deny
                Action:
                  - 'sagemaker:*'
                Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:user-profile/*/*'
                Condition:
                  NotIpAddress:
                    aws:VpcSourceIp: !Ref NetworkPrivateSubnet
        - PolicyName: AccessVPCResources
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeVpcs'
                Resource: !Sub '*'  
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName

Outputs:
  SageMakerExecutionRoleArn:
    Value: !GetAtt SageMakerExecutionRole.Arn
  SAMLBackEndLambdaRoleArn:
    Value: !GetAtt SAMLBackEndLambdaRole.Arn    
