AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sagemaker-stack

Parameters:
  
  SageMakerExecutionRoleArn:
    Type: String
  SageMakerDomainName:
    Type: String
  PrivateSubnetVPCSageMakerStudio: 
    Type: String
  SecurityGroupSageMakerStudio: 
    Type: String
  VPCSageMaker: 
    Type: String
  EnvironmentName: 
    Type: String
  SSOUserId: 
    Type: String
  DataScienceImage:
    Type: String
  DeleteSageMakerEFSArn:
    Type: String  

Resources:

  SageMakerStudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      AppNetworkAccessType: VpcOnly
      AuthMode: IAM
      DomainName: !Ref SageMakerDomainName
      SubnetIds:
        - !Ref PrivateSubnetVPCSageMakerStudio
      DefaultUserSettings:
          ExecutionRole: !Ref SageMakerExecutionRoleArn
          SecurityGroups:
            - !Ref SecurityGroupSageMakerStudio
      VpcId: !Ref VPCSageMaker
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName

  SageMakerStudioUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties: 
      DomainId: !GetAtt SageMakerStudioDomain.DomainId
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
      UserProfileName: !Ref SSOUserId

  JupyterApp:
    Type: AWS::SageMaker::App
    DependsOn: SageMakerStudioUserProfile
    Properties: 
      AppName: default
      AppType: JupyterServer
      DomainId: !GetAtt SageMakerStudioDomain.DomainId
      UserProfileName: !Ref SSOUserId
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
  
  DataScienceApp:
    Type: AWS::SageMaker::App
    DependsOn: SageMakerStudioUserProfile
    Properties: 
      AppName: instance-event-engine-datascience-ml-t3-medium
      AppType: KernelGateway
      DomainId: !GetAtt SageMakerStudioDomain.DomainId
      ResourceSpec: 
        InstanceType:  ml.t3.medium
        SageMakerImageArn: !Ref DataScienceImage
      UserProfileName: !Ref SSOUserId
      Tags: 
        - Key: EnvironmentName
          Value: !Ref EnvironmentName        

  DeleteEFSSageMaker:
    Type: Custom::DeleteEFSSageMaker
    Properties:
      ServiceToken: !Ref DeleteSageMakerEFSArn
      DomainId: !GetAtt SageMakerStudioDomain.DomainId
      vpcId: !Ref VPCSageMaker

Outputs:
  SageMakerStudioDomainId:
    Description: "SageMaker Studio domain created"
    Value: !GetAtt SageMakerStudioDomain.DomainId